envin = 'dev'
logger = None
date_folder = None
expected_map = {}
expected_norms = {}
expected_app = {}
expected_app_by_folder = {}
app_res_by_id = {}
random_geo_data_per_vendor = {}
cities_counties_white_dict = {}
city_to_areaid = {}
expected_by_folder = {}
agents_selected_per_vendor = {}
used_ids = {}
neigborhood_sampled = {}
dup_ids = {}
mongo_res_photos_count = {}
postg_res_photos_count = {}
mongo_res_open_house_count = {}
postg_res_open_house_count = {}
mongo_res_expert_info = {}
postg_res_expert_info = {}
mongo_res_reali_house_status = {}
postg_res_reali_house_status = {}
dup_res_dict = {}
postg_res_dict = {}
postg_res_photos_dict = {}
redfin_res_full_dict = None
region_type = None
total_sum_final_mis_list = 0
total_sum_duplicated_list = 0
total_sum_mis_city_list = 0
total_sum_not_valid_zipcode_list = 0
total_sum_not_valid_comps_proxy_status_list = 0
total_sum_not_valid_house_type_list = 0
total_sum_not_valid_listing_price_list = 0
total_sum_is_filter_list = 0
total_sum_not_valid_reali_house_status_list = 0
total_sum_list_miss_photos_count = 0
total_sum_miss_key_numeric_info = 0
total_sum_mis_lis = 0
total_sum_plus_lis = 0
total_properties_count_in_source_per_mls = 0
total_properties_count_in_source = 0
total_sum_of_zip_code_coverage = 0
total_sum_of_zip_code_coverage_of_mis_list = 0
total_sum_of_zip_code_coverage_of_plus_list = 0
len_of_mongo_res_listing_dict = 0

existance_listings = {}  # valid listings that are in both mongo and mls - will be used for photos and open house verification

summary = {}
mis_lis = []
plus_lis = []
duplicate_count = 0
postg_res_count = 0

# from_source_count will replace postg_res_count
from_source_count = 0
mis_city = []
no_assets = []
is_app_in_mongo = 0

aws_secrets = {}
all_from_meta = {}
broken_lis = []
vendor = 'wn_elad'
redfin_count = 0
